cambio automatico valores yaml3

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -50,14 +50,26 @@ jobs:
         uses: EndBug/add-and-commit@v9
         with:
           message: 'Updates values.yaml with commit ${{ needs.ci.outputs.commit_id }}'
-      -
+      - 
         name: Install argocd
         shell: bash
         run: |
-          curl -ksSl -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
+          # 1. Descarga con -L (seguir redirecciones) y -f (fallar si no existe)
+          # NOTA: Asegúrate de que termine en amd64
+          curl -sSLf -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
+          
+          # 2. Verificar si el archivo tiene tamaño (si bajó algo)
+          if [ ! -s argocd ]; then
+            echo "ERROR: El archivo argocd está vacío o no se descargó"
+            exit 1
+          fi
+          
+          # 3. Dar permisos y mover
           chmod +x argocd
           sudo mv ./argocd /usr/bin/argocd
-          ls -la /usr/bin/
+          
+          # 4. Prueba final: imprimir la versión
+          argocd version --client
       -
         name: argocd app sync
         shell: bash
